erDiagram
    users {
        UUID user_id PK
        VARCHAR(30) nickname UK
        VARCHAR(100) full_name
        TEXT email UK
        TEXT google_id UK
        TEXT bio
        TEXT password_hash
        TEXT avatar_url
        TEXT[] social_networks
        INTEGER max_streak
        TEXT timezone
        DATE last_watch_date
        TEXT profile_frame_url
        TEXT profile_background_url
        user_status_enum user_status
        TIMESTAMP crated_at
        TIMESTAMP updated_at
    }

    animes {
        UUID anime_id PK
        TEXT slug UK
        TEXT title_ua
        TEXT title_en
        TEXT title_original
        TEXT anime_description
        TEXT cover_url
        TEXT production_studio
        INT mal_id
        INT anilist_id
        INT hikka_id
        INT imdb_id
        INT year_released
        INT avg_episode_duration
        mpaa_rating_enum age_restriction
        anime_status_enum anime_status
        anime_format_enum anime_format
        BOOLEAN available
    }

    animeListUnits {
        UUID user_id PK, FK
        UUID anime_id PK, FK
        INTEGER watched_episodes
        INTEGER repeat_times
        DATE started_watching
        anime_list_unit_status_enum list_unit_status
    }

    comments {
        BIGINT comment_id PK
        UUID author_id FK
        UUID anime_id FK
        SMALLINT grade
        TEXT content
        TIMESTAMP created_at
    }

    episodes {
        BIGINT episode_id PK
        UUID anime_id FK
        TEXT source_url
        TEXT episode_name
        TEXT localization_studio
        localization_type_enum localization_type
    }

    genres {
        UUID anime_id FK
        genre_type genre_type UK
    }

    sessions {
        BIGINT session_id PK
        UUID user_id FK
        CHAR(128) refresh_token UK
        TEXT device_type
        TEXT device_name
        TEXT os
        TEXT browser
        TEXT user_agent
        TEXT user_location
        INET ip_address
    }

    upcomingEpisodes {
        UUID anime_id PK, FK
        TEXT episode_name
        TIMESTAMP episode_date PK
    }

    rooms_REDIS_ {
        TEXT room_code PK
        UUID owner_id FK
        UUID[] participants
        BIGINT[] playlist
        TIMESTAMP play_timestamp
        INTEGER play_offset
        BOOLEAN playing
        BOOLEAN public
    }

    users ||--o{ comments : "writes"
    users ||--o{ animeListUnits : "associates"
    users ||--o{ sessions : "authorizes"
    animes ||--o{ animeListUnits : "associates"
    animes ||--o{ comments : "has"
    animes ||--o{ episodes : "has"
    animes ||--o{ upcomingEpisodes : "has"
    animes ||--o{ genres : "has"
    rooms_REDIS_ |o--|{ users : "has"
    rooms_REDIS_ |o--|| users : "owned by"
    rooms_REDIS_ }o--o{ episodes : "playing"