version: '3.8'

services:
  postgres:
    image: postgres:17.5-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - ../data:/tmp/data
      - ../dumps:/tmp/dumps
      - ../scripts/create-campus-tables.sql:/tmp/scripts/create-campus-tables.sql
      - ./insert_data.sh:/tmp/scripts/insert_data.sh
    networks:
      - db-network

networks:
  db-network:
    driver: bridge
