#!/usr/bin/env bash

DIRNAME=$(dirname "$0")
MDFILE="$DIRNAME/queries/$1.md"
MDFILE_PLURAL="$DIRNAME/queries/$1s.md"

CONTENT=$(cat "$MDFILE" 2> /dev/null || cat "$MDFILE_PLURAL" 2> /dev/null) \
  || (echo "Available options:"; ls "$DIRNAME/queries" | awk -F. '{ print "-", $1 }')

echo "$CONTENT" | awk '/^```[sS][qQ][lL]/ { print ""; flag=1; next } /```/ { if (flag) { flag=0; print ""; next } } flag; /^## / { sub(/^#+/, "---"); print toupper($0) }; /^### / { sub(/^#+/, "---"); print }';
